# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/
version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    goimports:
      local-prefixes:
        - github.com/sunerpy/requests

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - bodyclose
    - noctx
    - prealloc

  settings:
    errcheck:
      check-type-assertions: false
      check-blank: false

    govet:
      disable:
        - fieldalignment
      enable:
        - shadow

    misspell:
      locale: US

    prealloc:
      simple: true
      range-loops: true
      for-loops: false

  exclusions:
    generated: lax
    presets:
      - comments
      - std-error-handling
    rules:
      # Exclude some linters from running on tests files
      - path: _test\.go
        linters:
          - errcheck
          - bodyclose
          - noctx

      # Exclude staticcheck SA1029 (context key type) in test files
      - path: _test\.go
        text: "SA1029"
        linters:
          - staticcheck

      # Exclude staticcheck S1008 (simplify return) in test files
      - path: _test\.go
        text: "S1008"
        linters:
          - staticcheck

      # Exclude staticcheck ST1023 (omit type) - style preference
      - text: "ST1023"
        linters:
          - staticcheck

      # Exclude example directory
      - path: example/
        linters:
          - errcheck

      # Exclude vendor directory
      - path: vendor/
        linters:
          - all

      # Exclude benchmark tests from noctx
      - path: test/benchmark_test\.go
        linters:
          - noctx

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
