name: Deploy GitHub Pages

on:
  push:
    branches:
      - gh-pages  # Pages 部署由 gh-pages 分支触发

jobs:
  deploy-pages:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v3
      with:
        ref: gh-pages  # 确保拉取 gh-pages 分支

    - name: Ensure benchmark results are stored
      run: |
        if [ ! -f dev/bench/index.html ] || [ ! -f dev/bench/data.js ]; then
          echo "Benchmark results not found in dev/bench directory!"
          exit 1
        fi
        # mkdir -p dev/bench
        # cp output.txt dev/bench/output.txt
        # if [ ! -f dev/bench/output.txt ]; then
        #   echo "Benchmark results not found in gh-pages branch!"
        #   exit 1
        # fi

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./  # 根目录中包含 Pages 的内容
